# Generated by Django 5.2.12 on 2026-04-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='memories/', verbose_name='Фото'),
        ),
    ]
